/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.4.2-119-g41315d5c7d"
#endif /* AVUTIL_FFVERSION_H */
